### ISSUE TITLE
1.16.1 item meta can't cast into map meta

### ISSUE THREAD

**Issue by kate-gg** [JohnnyJayJay/spigot-maps#10] opened 2020-08-08 15:19 UTC
1.16.1 server item meta can't cast into map meta

**To Reproduce**
1. Using 1.16.1 (purpur fork) server 
2. create map itemstack form libary

**Expected behavior**
create an map itemstack

**Screenshots, Code & Stack Traces**
"java.lang.ClassCastException: org.bukkit.craftbukkit.v1_16_R1.inventory.CraftMetaItem cannot be cast to org.bukkit.inventory.meta.MapMeta"

**Spigot Version:**
Purpur-1.16.1

**Comment by JohnnyJayJay** [comment] 2020-08-22 11:59
Sorry for the late response, I didn't receive a notification for this issue. 

I cannot reproduce your issue, I'm afraid. Can you send more context, such as some code and your build.gradle/pom.xml?

**Comment by JohnnyJayJay** [comment] 2020-08-22 13:07
Also, the full stack trace would be helpful.

**Comment by kate-gg** [comment] 2020-08-22 17:06
I lost the code now,
but it problem of casting **v1_16_R1.inventory.CraftMetaItem** to **org.bukkit.inventory.meta.MapMeta**
I change an code a bit from **v1_16_R1.inventory.CraftMetaItem** to **Bukkit itemMeta** and it's fixed an issue on 1.16.1

**Comment by JohnnyJayJay** [comment] 2020-08-22 17:08
Well, as I said, everything works fine for me on 1.16.1. Without code, stack trace and further information about the environment I can't do much unfortunately.

**Comment by kate-gg** [comment] 2020-08-22 17:11
then i think an issue is from purpur itself
thank for reply

**Comment by JohnnyJayJay** [comment] 2020-08-22 20:45
I actually don't think that. Another person seems to have the same issue and they don't use purpur.

**Comment by JohnnyJayJay** [comment] 2020-08-22 20:47
I'll leave this issue open for now, in case you come back to it or someone else experiences the same, just reply here again.

**Comment by ChristianDouglas** [comment] 2020-08-23 05:49
https://paste.helpch.at/ijenivuhof.md

Heres my full stack trace, here is my grade build file https://paste.helpch.at/funetitiza.coffeescript

**Comment by JohnnyJayJay** [comment] 2020-08-24 08:57
I did not mean to close this issue with the above commit lol. But thanks to @Aj3douglas 's help we seem to have identified the issue. The reason is that `Material.MAP` is not the correct material for non-legacy API versions. When I tested it, I used a legacy API version and therefore it was replaced by `Material.LEGACY_MAP`, which works correctly. There is now a version check in this.

**Comment by kate-gg** [comment] 2020-08-25 16:22
Didn't you try `Material.FILLED_MAP`

**Comment by JohnnyJayJay** [comment] 2020-08-25 16:33
See commit 04bc7d6 .

**Closed as completed** 2020-09-05 04:05 UTC
Labels: bug
